### ISSUE TITLE
Deploying portfolio website for production

### ISSUE THREAD

**Issue by edenlisk** [edenlisk/edenlisk.github.io#1]
Deployed website using GitHub pages

**Comment by mckent05** [comment]
Hi @edenlisk,

# STATUS: APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/200527858-b325ac87-f98a-48cd-bae1-9a1b77424f08.gif)

## Highlights
- Project deployed properly 👍 👍 
- Live version of your project works well 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
